# Automatically generated by depends.py.

##################
# Test namelists #
##################

TESTNML = checks.nml convergence.nml fmad.nml ga.nml genunits_data.nml genunits_io.nml port.nml prec.nml purerng.nml rev.nml timer.nml units.nml units_ad.nml unittest.nml
.PRECIOUS: $(TESTNML)

####################
# All source files #
####################

ALLSRC = app$(DIR_SEP)geninput.f90 app$(DIR_SEP)genunits.f90 mk$(DIR_SEP)before.mk mk$(DIR_SEP)build.md mk$(DIR_SEP)common.mk mk$(DIR_SEP)crayftn.mk mk$(DIR_SEP)depends.mk mk$(DIR_SEP)flang.mk mk$(DIR_SEP)gfortran.mk mk$(DIR_SEP)ifort_linux.mk mk$(DIR_SEP)ifort_windows.mk mk$(DIR_SEP)ifx_linux.mk mk$(DIR_SEP)ifx_windows.mk mk$(DIR_SEP)lfortran.mk mk$(DIR_SEP)linux_2.mk mk$(DIR_SEP)linux_defaults.mk mk$(DIR_SEP)manual.mk mk$(DIR_SEP)nagfor.mk mk$(DIR_SEP)nvfortran.mk mk$(DIR_SEP)windows_2.mk mk$(DIR_SEP)windows_defaults.mk mk$(DIR_SEP)xlf.mk src$(DIR_SEP)checks.f90 src$(DIR_SEP)cli.f90 src$(DIR_SEP)convergence.f90 src$(DIR_SEP)debug.f90 src$(DIR_SEP)fmad.f90 src$(DIR_SEP)ga.f90 src$(DIR_SEP)geninput_subroutine.f90 src$(DIR_SEP)geninput_type.f90 src$(DIR_SEP)genunits_data.f90 src$(DIR_SEP)genunits_io.f90 src$(DIR_SEP)port.f90 src$(DIR_SEP)prec.f90 src$(DIR_SEP)purerng.f90 src$(DIR_SEP)release.f90 src$(DIR_SEP)stopcodes.f90 src$(DIR_SEP)timer.f90 src$(DIR_SEP)unittest.f90 test$(DIR_SEP)genunits_input.nml test$(DIR_SEP)genunits_input_ad.nml test$(DIR_SEP)test_assert_dimension_false_1.f90 test$(DIR_SEP)test_assert_dimension_false_2.f90 test$(DIR_SEP)test_assert_dimension_false_3.f90 test$(DIR_SEP)test_assert_false_1.f90 test$(DIR_SEP)test_assert_false_2.f90 test$(DIR_SEP)test_checks.f90 test$(DIR_SEP)test_convergence.f90 test$(DIR_SEP)test_fmad.f90 test$(DIR_SEP)test_ga.f90 test$(DIR_SEP)test_genunits_data.f90 test$(DIR_SEP)test_genunits_io.f90 test$(DIR_SEP)test_port.f90 test$(DIR_SEP)test_prec.f90 test$(DIR_SEP)test_purerng.f90 test$(DIR_SEP)test_rev.f90 test$(DIR_SEP)test_timer.f90 test$(DIR_SEP)test_units.f90 test$(DIR_SEP)test_units_ad.f90 test$(DIR_SEP)test_units_fail_1.f90 test$(DIR_SEP)test_units_fail_2.f90 test$(DIR_SEP)test_units_fail_3.f90 test$(DIR_SEP)test_units_fail_4.f90 test$(DIR_SEP)test_unittest.f90