# Automatically generated by depends.py.

##################
# Test namelists #
##################

TESTNML = autodiff.nml checks.nml genunits_data.nml genunits_io.nml nmllog.nml port.nml prec.nml purerng.nml timer.nml units.nml unittest.nml
.PRECIOUS: $(TESTNML)