# Summary: Common Makefile for FLT
# Standard: POSIX (tested on GNU Make, BSD Make, pdpmake, and Microsoft NMAKE)
# Author: Ben Trettel (<http://trettel.us/>)
# Project: [flt](https://github.com/btrettel/flt)
# License: [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)

# Add later: dimmod.nml ga.nml
TESTNML = autodiff.nml checks.nml genunits_data.nml genunits_io.nml nmllog.nml port.nml prec.nml purerng.nml timer.nml units.nml unittest.nml
.PRECIOUS: $(TESTNML)

###############
# Boilerplate #
###############

.SUFFIXES:
.SUFFIXES: .f90 .$(OBJEXT)

.f90.$(OBJEXT):
	$(FC) $(OBJFLAGS) $@ $(FFLAGS) $<

.PHONY: test
test: $(TESTNML)
	@echo =====================
	@echo = All tests passed. =
	@echo =====================
	@echo Compiler: $(FC)

.PHONY: clean
clean:
	-$(RM) $(CLEAN)

#######################
# Manual dependencies #
#######################

# Needs to be manually present as this is autogenerated and not available for depends.py to find.
src$(DIR_SEP)units.f90: genunits$(BINEXT) test$(DIR_SEP)genunits_input.nml
	$(RUN)genunits$(BINEXT) test$(DIR_SEP)genunits_input.nml

src$(DIR_SEP)units.$(OBJEXT): src$(DIR_SEP)prec.$(OBJEXT)

# Additional dependencies beyond the autogenerated dependencies.
checks.nml: test_assert_false$(BINEXT) test_assert_false_message$(BINEXT) test_assert_dimension_false_1$(BINEXT) test_assert_dimension_false_2$(BINEXT) test_assert_dimension_false_3$(BINEXT)

genunits_io.nml: test$(DIR_SEP)genunits_input.nml

units.nml: test$(DIR_SEP)test_units_fail_1.f90 test$(DIR_SEP)test_units_fail_2.f90

unittest.nml: prec.nml

###########################
# Portable Python scripts #
###########################

.PHONY: f90lint
f90lint:
	$(PYTHON) py$(DIR_SEP)f90lint.py app$(DIR_SEP)*.f90 src$(DIR_SEP)*.f90 test$(DIR_SEP)*.f90

.PHONY: depends
depends:
	$(PYTHON) py$(DIR_SEP)depends.py app$(DIR_SEP)*.f90 src$(DIR_SEP)*.f90 test$(DIR_SEP)*.f90
